### ISSUE TITLE
New AM Source Code

### ISSUE THREAD

**Issue by Meetem** [JoelTroch/am_src_30jan2011#1]
Hey, buddy. Long time no see :) 

I have repository on bitbucket with latest Arrangement code. I can share it if you want, for archive purposes.

**Comment by JoelTroch** [comment]
Hello :)

I have access to that same repo too, we need to ask SysOp first before sharing it to the public.

**Comment by Meetem** [comment]
Oh, you are right. Can you reach to him? I’am just downloaded HLSDK, will
try to play with it again, after so much years.

**Comment by JoelTroch** [comment]
Hey @Meetem ,

I talked to SysOp and he gave me the go ahead to setup the repository and release the code.

One question for you before I release the thing to the public: how would you like to be credited?

**Comment by Meetem** [comment]
It’s out mutual work, so accordingly to features :) I’ve mostly did
graphics stuff.
If you are talking about open/closed source, I'am fine with open-sourcing it. With freedom to copy and reproduce. 
Btw I’am working now on new renderer for HL, do you have interest to see it?

**Comment by JoelTroch** [comment]
Latest source code is live for the public: https://github.com/JoelTroch/am_src_latest

These days I wish for a renderer that keeps the HL1 visuals but better performance wise :)
